workflows: added a step to fix macOS file pathing issues

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -45,6 +45,17 @@ jobs:
           sdkmanager --install "platform-tools" "cmdline-tools;latest"
           echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
 
+      - name: Fix Android SDK Tool Path
+        run: |
+          # Clean up inconsistent cmdline-tools folders
+          cd $ANDROID_HOME/cmdline-tools
+          # Move whatever is in 'latest-2' into 'latest'
+          rm -rf latest
+          mv latest-2 latest || true
+          # Add the correct bin to PATH
+          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
+          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
+
       - name: Run connected tests
         uses: ReactiveCircus/android-emulator-runner@v2
         with:
